import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { ReactQueryClientProvider } from "@/components/react-query-qlient-provider";
import { ToastProvider } from '@/components/providers/toaster-provider';

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider >
      <ClerkProvider>
        <html lang="en">
          <body className={inter.className}>
            <ToastProvider/>
            {children}
          </body>
        </html>
      </ClerkProvider>
    </ReactQueryClientProvider>
    
    
  );
}
